# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'path_visualization.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(520, 560)
        self.map_graphicsView = QtWidgets.QGraphicsView(Form)
        self.map_graphicsView.setGeometry(QtCore.QRect(10, 10, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_graphicsView.sizePolicy().hasHeightForWidth())
        self.map_graphicsView.setSizePolicy(sizePolicy)
        self.map_graphicsView.setMinimumSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setBaseSize(QtCore.QSize(500, 500))
        self.map_graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.map_graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 500.0, 500.0))
        self.map_graphicsView.setObjectName("map_graphicsView")
        self.calculate_path_pushButton = QtWidgets.QPushButton(Form)
        self.calculate_path_pushButton.setGeometry(QtCore.QRect(10, 520, 111, 31))
        self.calculate_path_pushButton.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.calculate_path_pushButton.setObjectName("calculate_path_pushButton")
        self.path_following_pushButton = QtWidgets.QPushButton(Form)
        self.path_following_pushButton.setGeometry(QtCore.QRect(130, 520, 111, 31))
        self.path_following_pushButton.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.path_following_pushButton.setObjectName("path_following_pushButton")
        self.Env_Number_spinBox = QtWidgets.QSpinBox(Form)
        self.Env_Number_spinBox.setGeometry(QtCore.QRect(430, 520, 81, 31))
        self.Env_Number_spinBox.setMaximum(300)
        self.Env_Number_spinBox.setObjectName("Env_Number_spinBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(316, 525, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.calculate_path_pushButton.clicked.connect(Form.calculate_path) # type: ignore
        self.path_following_pushButton.clicked.connect(Form.path_following) # type: ignore
        self.Env_Number_spinBox.valueChanged['int'].connect(Form.stage_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Path Visualization and Control"))
        self.calculate_path_pushButton.setText(_translate("Form", "calculate path"))
        self.path_following_pushButton.setText(_translate("Form", "path following"))
        self.label.setText(_translate("Form", "Test Env No."))
